name: Build Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build server
        working-directory: ./server
        run: |
          npm install
          npm run build

      - name: Build client
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Organize dist folder
        run: |
          # Create root dist folder if it doesn't exist
          mkdir -p dist

          # Copy server/dist to root dist
          cp -r server/dist/* dist/

          # Create public folder in root dist
          mkdir -p dist/public

          # Copy client/dist to dist/public
          cp -r client/dist/* dist/public/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
