name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for Server
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install Server Dependencies
        run: |
          cd server
          npm ci

      - name: Run Server Tests with Coverage
        run: |
          cd server
          npm run test:cov
          
      - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          name: 'backend-coverage-report'
          working-directory: server

      - name: Build Server
        run: |
          cd server
          npm run build
      
      - name: Setup Node.js for Client
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install Client Dependencies
        run: |
          cd client
          npm ci
      
      - name: Build Client
        run: |
          cd client
          npm run build
      
      - name: Create app directory structure
        run: |          
          echo "Application assembled successfully"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zizifn/interview-quiz:1.0.${{ github.run_number }},zizifn/interview-quiz:latest
